### ISSUE TITLE
Add a README

### ISSUE THREAD

**Issue by principalkelvo** [Octal-Ideas/octal-educators#5]

**Comment by Pauline-njuguna** [comment]
# OCTAL EDUCATORS

# By: OCTAL IDEAS

# Project Description

This is a school website that enables you to book different available IT courses. The website utilizes the Vite framework to create a seamless user experience.

# Setup/Installation Requirements

Clone the repository from GitHub.

Navigate to the root directory of the project.

Run npm install to install all the dependencies.

Run npm run dev to start the development server.

Open your browser and go to localhost:3000 to view the application.

# BDD
As a user:

I want to be able to view the available IT courses on the website. 

I want to be able to select and book a course of my choice.

I want to be able to view my bookings and edit them if necessary.

# Live Link
https://octal-educators.vercel.app/

# Bugs
There are currently no known bugs in the project.

# Technologies Used
HTML

CSS

JavaScript

Vite

# Support/Contact Details

If you encounter any issues or would like to reach out to the project creator, please feel free to send an email to octalideas@gmail.com

# License

This project is licensed under the MIT License.
